### ISSUE TITLE
Update grunt-laxar version

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/grunt-init-laxar-application#22]
Currently the `grunt-laxar` version inside the `package.json` file created by this template points to ~0.5.2. Unfortunately this version does not yet work properly on Windows.

The latest version is 0.7.0 and contains some fixes that address this problem so we should use that one (or better: any 0.x).

See #35, #36

**Comment by x1B** [comment]
Implemented on `master` (`v0.4.0`).
