### ISSUE TITLE
Upgrade template for new-style controls

### ISSUE THREAD

**Issue by x1B** [LaxarJS/grunt-init-laxar-application#26]
We should upgrade the LaxarJS application template to reflect the following changes:

- LaxarJS/laxar#197
- LaxarJS/grunt-laxar#55
- LaxarJS/laxar#133
- LaxarJS/laxar-patterns#39

- The file listing patterns in the Gruntfile should be cleaned up and simplified.

**Comment by alex3683** [comment]
Furthermore:
- https://github.com/LaxarJS/laxar/issues/202

**Comment by x1B** [comment]
Implemented on `master` (`v1.0.0-beta.0`).
